from os import getenv
from dotenv import load_dotenv

load_dotenv()

API_HOST = getenv('API_HOST')
API_PORT = getenv('API_PORT')
API_URL = API_HOST + ':' + API_PORT

POSTGRES_SERVER = getenv('POSTGRES_SERVER')
POSTGRES_PORT = getenv('POSTGRES_PORT')
POSTGRES_DB = getenv('POSTGRES_DB')
POSTGRES_USER = getenv('POSTGRES_USER')
POSTGRES_PASSWORD = getenv('POSTGRES_PASSWORD')
POSTGRES_URL = f'postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}' \
               f'@{POSTGRES_SERVER}:{POSTGRES_PORT}/{POSTGRES_DB}'
POSTGRES_URL_ASYNC = f'postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}' \
                     f'@{POSTGRES_SERVER}:{POSTGRES_PORT}/{POSTGRES_DB}'

JWT_ALGORITHM = getenv('JWT_ALGORITHM')
JWT_SECRET_KEY = getenv('JWT_SECRET_KEY')
ACCESS_TOKEN_EXPIRE_MINUTES = int(getenv('ACCESS_TOKEN_EXPIRE_MINUTES'))

EMAIL_USERNAME = getenv('EMAIL_USERNAME')
EMAIL_PASSWORD = getenv('EMAIL_PASSWORD')

SERIALIZER_KEY = getenv('SERIALIZER_KEY')
