from os import getenv
from dotenv import load_dotenv

load_dotenv()

POSTGRES_SERVER = getenv('POSTGRES_SERVER')
POSTGRES_PORT = getenv('POSTGRES_PORT')
POSTGRES_DB = getenv('POSTGRES_DB')
POSTGRES_USER = getenv('POSTGRES_USER')
POSTGRES_PASSWORD = getenv('POSTGRES_PASSWORD')
POSTGRES_URL = f'postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_SERVER}:{POSTGRES_PORT}/{POSTGRES_DB}'

JWT_ALGORITHM = getenv('JWT_ALGORITHM')
JWT_SECRET_KEY = getenv('JWT_SECRET_KEY')
ACCESS_TOKEN_EXPIRE_MINUTES = getenv('ACCESS_TOKEN_EXPIRE_MINUTES')
